apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uk-data-pvc
  namespace: monitor
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi

