apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kv-config-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kv-comics-pvc
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: nfs
  volumeName: kavita-comics-pv
  resources:
    requests:
      storage: 25Gi
