resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml  

namePrefix: mealie-
  
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app: mealie
  
namespace: org
    
patches:
  - target:
      kind: Deployment
      name: deployment
    path: patches/diun-annotation.yaml
#  Uncomment to let traefik handle ssl certs
#  - target:
#      kind: Ingress
#      name: ingress
#    path: patches/traefik-ssl-cert.yaml
