apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc
  namespace: org
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: pv
  resources:
    requests:
      storage: 200Mi
