apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - name: filebrowser
        image: filebrowser
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "400m"
            memory: "500Mi"
          requests:
            cpu: "100m"
            memory: "250Mi"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /config
        - name: db
          mountPath: /database
        - name: stuff
          mountPath: /srv/gaurab_stuff
        - name: pictures
          mountPath: /srv/pictures
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config-pvc
      - name: db
        persistentVolumeClaim:
          claimName: db-pvc
      - name: stuff
        persistentVolumeClaim:
          claimName: stuff-pvc
      - name: pictures
        persistentVolumeClaim:
          claimName: pictures-pvc
