apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: config-pv
  resources:
    requests:
      storage: 5Gi
