apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nc-config-pvc
  namespace: org
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nc-storage-pvc
  namespace: org
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: nfs
  volumeName: nc-storage-pv
  resources:
    requests:
      storage: 100Gi
