apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgr-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi

 ---
 
 apiVersion: v1
 kind: PersistentVolumeClaim
 metadata:
   name: pgr-db-pvc
 spec:
   accessModes:
     - ReadWriteOnce
   storageClassName: longhorn
   resources:
     requests:
       storage: 10Mi
 
 ---
 
 apiVersion: v1
 kind: PersistentVolumeClaim
 metadata:
   name: pgr-tmp-pvc
 spec:
   accessModes:
     - ReadWriteOnce
   storageClassName: longhorn
   resources:
     requests:
       storage: 300Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgr-pictures-pvc
spec:
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  storageClassName: nfs
  volumeName: pgr-pictures-pv
  resources:
    requests:
      storage: 40Gi
