apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - name: ntfy
        image: ntfy
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "400m"
            memory: "400Mi"
          requests:
            cpu: "100m"
            memory: "100Mi"
        ports:
        - containerPort: 80
        command: ["ntfy", "serve"]
        envFrom:
        - configMapRef:
            name: map
        volumeMounts:
        - name: lib
          mountPath: /var/lib/ntfy
      volumes:
      - name: lib
        persistentVolumeClaim:
          claimName: lib-pvc
