resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - storage/longhorn.pv.yaml
  - storage/pvc.yaml

namePrefix: pihole-
  
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app: pihole
  
namespace: default

images:
- name: pihole
  newName: docker.io/mpgirro/pihole-unbound
  newTag: "2025.08.0"
    
configMapGenerator:
  - name: map
    env: env/properties
    files:
      - env/proxy-subdomains
    
secretGenerator:
  - name: secret
    env: env/passwords
    
patches:
  - target:
      kind: Deployment
      name: deployment
    path: patches/diun-annotation.yaml
  - target:
      kind: Deployment
      name: deployment
    path: patches/node-affinity.yaml
#  Uncomment to let traefik handle ssl certs
#  - target:
#      kind: Ingress
#      name: ingress
#    path: patches/traefik-ssl-cert.yaml

replacements:
- source:
    kind: PersistentVolume
    name: etc-pv
    fieldPath: metadata.name
  targets:
  - select:
      kind: PersistentVolume
      name: etc-pv
    fieldPaths:
    - spec.csi.volumeHandle
- source:
    kind: PersistentVolume
    name: dnsmasq-pv
    fieldPath: metadata.name
  targets:
  - select:
      kind: PersistentVolume
      name: dnsmasq-pv
    fieldPaths:
    - spec.csi.volumeHandle
