resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

namePrefix: pihole-
  
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app: pihole
  
namespace: default
    
configMapGenerator:
  - name: map
    env: env/properties
    files:
      - env/proxy-subdomains
    
secretGenerator:
  - name: secret
    env: env/passwords
    
patches:
  - target:
      kind: Deployment
      name: deployment
    path: patches/diun-annotation.yaml
  - target:
      kind: Deployment
      name: deployment
    path: patches/node-affinity.yaml
#  Uncomment to let traefik handle ssl certs
#  - target:
#      kind: Ingress
#      name: ingress
#    path: patches/traefik-ssl-cert.yaml
