apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wb-data-pvc
  namespace: org
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wb-images-pvc
  namespace: org
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
