apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - name: calibre
        image: lscr.io/linuxserver/calibre-web:0.6.25-ls345
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m"
            memory: "600Mi"
          requests:
            cpu: "100m"
            memory: "300Mi"
        ports:
        - containerPort: 8083
        env:
        - name: PUID
          valueFrom:
            configMapKeyRef:
              name: map
              key: user
        - name: PGID
          valueFrom:
            configMapKeyRef:
              name: map
              key: group
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: map
              key: timezone
        volumeMounts:
        - name: config
          mountPath: /config
        - name: books
          mountPath: /calibre-library
#       Ingest Directory, for automatic addition to library
#        - name: cw-ingest
#          mountPath: /cwa-book-ingest
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config-pvc
      - name: books
        persistentVolumeClaim:
          claimName: books-pvc
