resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - storage/longhorn.pv.yaml
  - storage/nfs.pv.yaml
  - storage/pvc.yaml

namePrefix: calibre-
  
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app: calibre
  - pairs:
      needs-media: "true"
  
namespace: media

images:
- name: calibre
  newName: lscr.io/linuxserver/calibre-web
  newTag: "0.6.25"
    
configMapGenerator:
  - name: map
    env: env/properties
    
patches:
  - target:
      kind: Deployment
      name: deployment
    path: patches/diun-annotation.yaml
#  Uncomment to let traefik handle ssl certs
#  - target:
#      kind: Ingress
#      name: ingress
#    path: patches/traefik-ssl-cert.yaml

replacements:
- source:
    kind: PersistentVolume
    name: config-pv
    fieldPath: metadata.name
  targets:
  - select:
      kind: PersistentVolume
      name: config-pv
    fieldPaths:
    - spec.csi.volumeHandle
