apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fr-data-pvc
  namespace: org
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
