apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
    spec:
      serviceAccountName: serviceaccount
      containers:
        - name: homarr
          image: ghcr.io/homarr-labs/homarr:v1.31.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "500m"
              memory: "500Mi"
            requests:
              cpu: "100m"
              memory: "200Mi"
          ports:
            - containerPort: 7575
          env:
#          - name: PUID
#            valueFrom:
#              configMapKeyRef:
#                name: map
#                key: user
#          - name: PGID
#            valueFrom:
#              configMapKeyRef:
#                name: map
#                key: group
          - name: SECRET_ENCRYPTION_KEY
            valueFrom:
              secretKeyRef:
                name: secret
                key: encryption-key
          - name: LOG_LEVEL
            value: warn
          volumeMounts:
            - name: config
              mountPath: /appdata
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: config-pvc
