apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etc-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: etc-pv
  resources:
    requests:
      storage: 500Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dnsmasq-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: dnsmasq-pv
  resources:
    requests:
      storage: 10Mi
