apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - name: searx
        image: searxng/searxng:2025.8.3-2e62eb5
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "800m"
            memory: "500Mi"
          requests:
            cpu: "150m"
            memory: "200Mi"
        ports:
        - containerPort: 8080
        env:
        - name: SEARXNG_BASE_URL
          valueFrom:
            configMapKeyRef:
              name: map
              key: base-url
        volumeMounts:
        - name: vol
          mountPath: /etc/searxng
      volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: pvc
