resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - storage/longhorn.pv.yaml
  - storage/pvc.yaml

namePrefix: searx-
  
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app: searx
  
namespace: util

images:
- name: searx
  newName: docker.io/searxng/searxng
  newTag: "2025.9.9-905b13a"

configMapGenerator:
  - name: map
    env: env/properties
    
patches:
  - target:
      kind: Deployment
      name: deployment
    path: patches/diun-annotation.yaml
#  Uncomment to let traefik handle ssl certs
#  - target:
#      kind: Ingress
#      name: ingress
#    path: patches/traefik-ssl-cert.yaml

replacements:
- source:
    kind: PersistentVolume
    name: pv
    fieldPath: metadata.name
  targets:
  - select:
      kind: PersistentVolume
      name: pv
    fieldPaths:
    - spec.csi.volumeHandle
