apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: privileged-client-role
rules:
- apiGroups:
  - ""
  - apps
  - autoscaling
  - batch
  - rbac.authorization.k8s.io
  - metrics.k8s.io
  - networking.k8s.io
  resources:
  - namespaces
  - pods
  - pods/log
  - pods/exec
  - pods/eviction
  - deployments
  - services
  - configmaps
  - secrets
  - replicasets
  - daemonsets
  - statefulsets
  - nodes
  - ingresses
  - namespace
  - events
  - jobs
  - cronjobs
  - persistentvolumes
  - persistentvolumeclaims
  - replicationcontrollers
  - horizontalpodautoscalers
  - roles
  - rolebindings
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - delete

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: privileged-client-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-client-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: privileged_client
