apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - name: mariadb
        image: mariadb
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "800m"
            memory: "800Mi"
          requests:
            cpu: "200m"
            memory: "400Mi"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: config
          mountPath: /config
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: root-password
        - name: PUID
          valueFrom:
            configMapKeyRef:
              name: map
              key: user
        - name: PGID
          valueFrom:
            configMapKeyRef:
              name: map
              key: group
        - name: TZ
          valueFrom:
            configMapKeyRef:
              name: map
              key: timezone
      
      - name: phpmyadmin   
        image: phpmyadmin
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret
              key: root-password
        - name: PMA_HOST
          valueFrom:
            configMapKeyRef:
              name: map
              key: mariadb-host
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: config-pvc
