resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - storage/longhorn.pv.yaml
  - storage/pvc.yaml

namePrefix: mariadb-
  
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app: mariadb
  
namespace: util

images:
- name: mariadb
  newName: lscr.io/linuxserver/mariadb
  newTag: "11.4.8"
- name: phpmyadmin
  newName: phpmyadmin/phpmyadmin
  newTag: "5.2.2"

configMapGenerator:
  - name: map
    env: env/properties
    
secretGenerator:
  - name: secret
    env: env/passwords
    
patches:
  - target:
      kind: Deployment
      name: deployment
    path: patches/diun-annotation.yaml
  - target:
      kind: Deployment
      name: deployment
    path: patches/node-affinity.yaml
#  Uncomment to let traefik handle ssl certs
#  - target:
#      kind: Ingress
#      name: ingress
#    path: patches/traefik-ssl-cert.yaml

replacements:
- source:
    kind: PersistentVolume
    name: config-pv
    fieldPath: metadata.name
  targets:
  - select:
      kind: PersistentVolume
      name: config-pv
    fieldPaths:
    - spec.csi.volumeHandle
