apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: config-pv
  resources:
    requests:
      storage: 10Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: db-pv
  resources:
    requests:
      storage: 10Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stuff-pvc
spec:
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  storageClassName: nfs
  volumeName: stuff-pv
  resources:
    requests:
      storage: 200Gi
      
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pictures-pvc
spec:
  accessModes:
    - ReadOnlyMany
  volumeMode: Filesystem
  storageClassName: nfs
  volumeName: pictures-pv
  resources:
    requests:
      storage: 50Gi
