apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-ipwhitelist
  namespace: default
spec:
  ipAllowList:
    sourceRange:
      - 192.168.1.0/24
    ipStrategy:
      depth: 1
