apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searx-pvc
  namespace: util
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Mi
