apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: data-pv
  resources:
    requests:
      storage: 100Mi
      
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeName: config-pv
  resources:
    requests:
      storage: 50Mi
